// Generated by gencpp from file robot_soccer/ballloc.msg
// DO NOT EDIT!


#ifndef ROBOT_SOCCER_MESSAGE_BALLLOC_H
#define ROBOT_SOCCER_MESSAGE_BALLLOC_H

#include <ros/service_traits.h>


#include <robot_soccer/balllocRequest.h>
#include <robot_soccer/balllocResponse.h>


namespace robot_soccer
{

struct ballloc
{

typedef balllocRequest Request;
typedef balllocResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ballloc
} // namespace robot_soccer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_soccer::ballloc > {
  static const char* value()
  {
    return "bfeed3c65524b12e19690fcc175741f8";
  }

  static const char* value(const ::robot_soccer::ballloc&) { return value(); }
};

template<>
struct DataType< ::robot_soccer::ballloc > {
  static const char* value()
  {
    return "robot_soccer/ballloc";
  }

  static const char* value(const ::robot_soccer::ballloc&) { return value(); }
};


// service_traits::MD5Sum< ::robot_soccer::balllocRequest> should match 
// service_traits::MD5Sum< ::robot_soccer::ballloc > 
template<>
struct MD5Sum< ::robot_soccer::balllocRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_soccer::ballloc >::value();
  }
  static const char* value(const ::robot_soccer::balllocRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_soccer::balllocRequest> should match 
// service_traits::DataType< ::robot_soccer::ballloc > 
template<>
struct DataType< ::robot_soccer::balllocRequest>
{
  static const char* value()
  {
    return DataType< ::robot_soccer::ballloc >::value();
  }
  static const char* value(const ::robot_soccer::balllocRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_soccer::balllocResponse> should match 
// service_traits::MD5Sum< ::robot_soccer::ballloc > 
template<>
struct MD5Sum< ::robot_soccer::balllocResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_soccer::ballloc >::value();
  }
  static const char* value(const ::robot_soccer::balllocResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_soccer::balllocResponse> should match 
// service_traits::DataType< ::robot_soccer::ballloc > 
template<>
struct DataType< ::robot_soccer::balllocResponse>
{
  static const char* value()
  {
    return DataType< ::robot_soccer::ballloc >::value();
  }
  static const char* value(const ::robot_soccer::balllocResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SOCCER_MESSAGE_BALLLOC_H
