// Generated by gencpp from file robot_soccer/home1locResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_SOCCER_MESSAGE_HOME1LOCRESPONSE_H
#define ROBOT_SOCCER_MESSAGE_HOME1LOCRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_soccer
{
template <class ContainerAllocator>
struct home1locResponse_
{
  typedef home1locResponse_<ContainerAllocator> Type;

  home1locResponse_()
    : timestamp(0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)
    , ball_x(0.0)
    , ball_y(0.0)  {
    }
  home1locResponse_(const ContainerAllocator& _alloc)
    : timestamp(0)
    , x(0.0)
    , y(0.0)
    , theta(0.0)
    , ball_x(0.0)
    , ball_y(0.0)  {
    }



   typedef int32_t _timestamp_type;
  _timestamp_type timestamp;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;

   typedef double _ball_x_type;
  _ball_x_type ball_x;

   typedef double _ball_y_type;
  _ball_y_type ball_y;




  typedef boost::shared_ptr< ::robot_soccer::home1locResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_soccer::home1locResponse_<ContainerAllocator> const> ConstPtr;

}; // struct home1locResponse_

typedef ::robot_soccer::home1locResponse_<std::allocator<void> > home1locResponse;

typedef boost::shared_ptr< ::robot_soccer::home1locResponse > home1locResponsePtr;
typedef boost::shared_ptr< ::robot_soccer::home1locResponse const> home1locResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_soccer::home1locResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_soccer::home1locResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_soccer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'robot_soccer': ['/home/odroid/catkin_ws/src/robot_soccer/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_soccer::home1locResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_soccer::home1locResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_soccer::home1locResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_soccer::home1locResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_soccer::home1locResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_soccer::home1locResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_soccer::home1locResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41a50ba430024c1e7282b7e27d56017c";
  }

  static const char* value(const ::robot_soccer::home1locResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41a50ba430024c1eULL;
  static const uint64_t static_value2 = 0x7282b7e27d56017cULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_soccer::home1locResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_soccer/home1locResponse";
  }

  static const char* value(const ::robot_soccer::home1locResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_soccer::home1locResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 timestamp\n\
float64 x\n\
float64 y\n\
float64 theta\n\
float64 ball_x\n\
float64 ball_y\n\
\n\
";
  }

  static const char* value(const ::robot_soccer::home1locResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_soccer::home1locResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
      stream.next(m.ball_x);
      stream.next(m.ball_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct home1locResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_soccer::home1locResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_soccer::home1locResponse_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
    s << indent << "ball_x: ";
    Printer<double>::stream(s, indent + "  ", v.ball_x);
    s << indent << "ball_y: ";
    Printer<double>::stream(s, indent + "  ", v.ball_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SOCCER_MESSAGE_HOME1LOCRESPONSE_H
