// Generated by gencpp from file robot_soccer/home1loc.msg
// DO NOT EDIT!


#ifndef ROBOT_SOCCER_MESSAGE_HOME1LOC_H
#define ROBOT_SOCCER_MESSAGE_HOME1LOC_H

#include <ros/service_traits.h>


#include <robot_soccer/home1locRequest.h>
#include <robot_soccer/home1locResponse.h>


namespace robot_soccer
{

struct home1loc
{

typedef home1locRequest Request;
typedef home1locResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct home1loc
} // namespace robot_soccer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_soccer::home1loc > {
  static const char* value()
  {
    return "41a50ba430024c1e7282b7e27d56017c";
  }

  static const char* value(const ::robot_soccer::home1loc&) { return value(); }
};

template<>
struct DataType< ::robot_soccer::home1loc > {
  static const char* value()
  {
    return "robot_soccer/home1loc";
  }

  static const char* value(const ::robot_soccer::home1loc&) { return value(); }
};


// service_traits::MD5Sum< ::robot_soccer::home1locRequest> should match 
// service_traits::MD5Sum< ::robot_soccer::home1loc > 
template<>
struct MD5Sum< ::robot_soccer::home1locRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_soccer::home1loc >::value();
  }
  static const char* value(const ::robot_soccer::home1locRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_soccer::home1locRequest> should match 
// service_traits::DataType< ::robot_soccer::home1loc > 
template<>
struct DataType< ::robot_soccer::home1locRequest>
{
  static const char* value()
  {
    return DataType< ::robot_soccer::home1loc >::value();
  }
  static const char* value(const ::robot_soccer::home1locRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_soccer::home1locResponse> should match 
// service_traits::MD5Sum< ::robot_soccer::home1loc > 
template<>
struct MD5Sum< ::robot_soccer::home1locResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_soccer::home1loc >::value();
  }
  static const char* value(const ::robot_soccer::home1locResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_soccer::home1locResponse> should match 
// service_traits::DataType< ::robot_soccer::home1loc > 
template<>
struct DataType< ::robot_soccer::home1locResponse>
{
  static const char* value()
  {
    return DataType< ::robot_soccer::home1loc >::value();
  }
  static const char* value(const ::robot_soccer::home1locResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_SOCCER_MESSAGE_HOME1LOC_H
