// Generated by gencpp from file robot_soccer/predictionsResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_SOCCER_MESSAGE_PREDICTIONSRESPONSE_H
#define ROBOT_SOCCER_MESSAGE_PREDICTIONSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_soccer
{
template <class ContainerAllocator>
struct predictionsResponse_
{
  typedef predictionsResponse_<ContainerAllocator> Type;

  predictionsResponse_()
    : home1_x(0)
    , home1_y(0)
    , home1_theta(0)
    , ball_x(0)
    , ball_y(0)  {
    }
  predictionsResponse_(const ContainerAllocator& _alloc)
    : home1_x(0)
    , home1_y(0)
    , home1_theta(0)
    , ball_x(0)
    , ball_y(0)  {
    }



   typedef int32_t _home1_x_type;
  _home1_x_type home1_x;

   typedef int32_t _home1_y_type;
  _home1_y_type home1_y;

   typedef int32_t _home1_theta_type;
  _home1_theta_type home1_theta;

   typedef int32_t _ball_x_type;
  _ball_x_type ball_x;

   typedef int32_t _ball_y_type;
  _ball_y_type ball_y;




  typedef boost::shared_ptr< ::robot_soccer::predictionsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_soccer::predictionsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct predictionsResponse_

typedef ::robot_soccer::predictionsResponse_<std::allocator<void> > predictionsResponse;

typedef boost::shared_ptr< ::robot_soccer::predictionsResponse > predictionsResponsePtr;
typedef boost::shared_ptr< ::robot_soccer::predictionsResponse const> predictionsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_soccer::predictionsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_soccer::predictionsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_soccer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'robot_soccer': ['/home/odroid/catkin_ws/src/robot_soccer/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_soccer::predictionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_soccer::predictionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_soccer::predictionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_soccer::predictionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_soccer::predictionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_soccer::predictionsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_soccer::predictionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82822e65ac84105b380cffacbff834f8";
  }

  static const char* value(const ::robot_soccer::predictionsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82822e65ac84105bULL;
  static const uint64_t static_value2 = 0x380cffacbff834f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_soccer::predictionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_soccer/predictionsResponse";
  }

  static const char* value(const ::robot_soccer::predictionsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_soccer::predictionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 home1_x\n\
int32 home1_y\n\
int32 home1_theta\n\
int32 ball_x\n\
int32 ball_y\n\
\n\
";
  }

  static const char* value(const ::robot_soccer::predictionsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_soccer::predictionsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.home1_x);
      stream.next(m.home1_y);
      stream.next(m.home1_theta);
      stream.next(m.ball_x);
      stream.next(m.ball_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct predictionsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_soccer::predictionsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_soccer::predictionsResponse_<ContainerAllocator>& v)
  {
    s << indent << "home1_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.home1_x);
    s << indent << "home1_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.home1_y);
    s << indent << "home1_theta: ";
    Printer<int32_t>::stream(s, indent + "  ", v.home1_theta);
    s << indent << "ball_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ball_x);
    s << indent << "ball_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ball_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SOCCER_MESSAGE_PREDICTIONSRESPONSE_H
